jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      token: 8BFU4HjN5yy9pJPqkOvweA
      script:
        - python hello_world.py
